# Generated by Django 6.0 on 2026-01-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1)),
                ('major', models.CharField(choices=[('O', '전공자'), ('X', '비전공자')], max_length=1)),
            ],
        ),
    ]
