# Generated by Django 6.0 on 2026-01-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
