# Generated by Django 6.0 on 2026-01-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.PositiveIntegerField(help_text='몇 주차인지 (예: 1주차, 2주차)', verbose_name='주차')),
                ('team_count', models.PositiveIntegerField(help_text='해당 주차의 팀 개수', verbose_name='팀 개수')),
                ('pr_name', models.CharField(help_text='해당 주차 프로젝트 / 과제 이름', max_length=100, verbose_name='과제명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '주차',
                'verbose_name_plural': '주차 목록',
                'db_table': 'week',
                'ordering': ['week_no'],
                'unique_together': {('week_no', 'pr_name')},
            },
        ),
    ]
