# Generated by Django 6.0 on 2026-01-05 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('weeks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.PositiveIntegerField()),
                ('team_score', models.FloatField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='weeks.week')),
            ],
            options={
                'db_table': 'team',
                'unique_together': {('week', 'team_no')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='members.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'db_table': 'team_member',
                'unique_together': {('team', 'member')},
            },
        ),
    ]
